### ISSUE TITLE
trait NextTime is private

### ISSUE THREAD

**Issue by Elrendio** [mdsherry/clokwerk#10]
Hello,

first thanks a lot for the crate ! I was wondering why the trait `NextTime` is private ?

Here's my use case for why I would like it to be public:
 - We have a library than spans a small server with some scheduled job scheduled with clokwerk.
 - We would like at every Interval to load all the events from the last 2 intervals. For that we need to provide a filter with a field `start_date` and would have liked to use:

```rust
use {
	clokwerk::{NextTime, Interval, TimeUnits},
	chrono::{DateTime, Utc},
};
// In reality load the interval from the servers' config
let my_interval = 5.minutes();

// When booting the server
let mut schedule = Scheduler::new();
schedule
	.every(my_interval)
	.run(move || {
		let now = Utc::now();

		let prev = my_interval.prev();

		let start_date = now - 2 * (now - prev);

		// Filter based on start_date ...
	});
```

If you accept to make `NextTime` public I can submit a PR :) 

Have a nice day !

**Comment by mdsherry** [comment]
The `NextTime` trait should now be public, as of `clokwerk` 0.3.0
