### ISSUE TITLE
Multiple jobs on schedule with synchronous code leads to other jobs not kicking off + possibility of adding a "stop after" propety

### ISSUE THREAD

**Issue by joshterrill** [mdsherry/clokwerk#11]
I've got some code that looks like this:

```rust
    let mut scheduler = Scheduler::new();
    scheduler.every(Weekday).at("04:00").run(|| {
        for _ in 1..50 {
            cache_news();
            thread::sleep(Duration::from_secs(600));
        }
    });
    scheduler.every(Weekday).at("04:20").run(|| {
        for _ in 1..31 {
            cache_high_low();
            thread::sleep(Duration::from_secs(600));
        }
    });
    let _thread_handle = scheduler.watch_thread(Duration::from_millis(100));
    loop {
        thread::sleep(Duration::from_millis(1000));
    }
```

I've got the for loops in there because I essentially want to say "Run this every weekday starting at x time, run it y number of times, at a 10 minute interval (600 seconds)

Unless there is another way, I think it would be really cool if the API supported a `stop_after(x)` method which told it after 10 runs or 10 minutes, to stop so that I didn't have to do this.

The other issue that I had was because the code in the jobs are synchronous, it's blocking on the thread, so whatever one fires first, in this case, the top one, the bottom one never ends up starting when it should.

I could just create separate schedules for all of my jobs that spawn their own threads, but that would mean that the threads would stay open for all of my jobs for the entirety of the program running (which is all the time). I thought it might have been a little overkill. What I ended up coming up with was:

```rust
    let mut scheduler = Scheduler::new();
    scheduler.every(Weekday).at("04:00").run(|| {
        thread::spawn(|| {
            for _ in 1..50 {
                cache_news();
                thread::sleep(Duration::from_secs(600));
            }
        });
    });
    scheduler.every(Weekday).at("04:20").run(|| {
        thread::spawn(|| {
            for _ in 1..31 {
                cache_high_low();
                thread::sleep(Duration::from_secs(600));
            }
        });
    });
    let _thread_handle = scheduler.watch_thread(Duration::from_millis(100));
    loop {
        thread::sleep(Duration::from_millis(1000));
    }
```

So threads get spawned inside of the job where the work is being done in the event that the code in there is synchronous. I think it would be cool if there was an additional method to `run()` like `run_as_own_thread()` or something (less verbose) which would accomplish what I'm trying to do here.

If either of these suggestions are something of interest, I could *try* my best to do a pull request. But I'd also understand if you think that these issues are outside of the scope of the problem that this library is trying to solve. I do love the library, by the way!

**Comment by mdsherry** [comment]
I would expect `stop_after(x)` to run the job once every weekday at 4 AM, but stop after the `x`th day. Perhaps
```rust
scheduler.every(Weekday).at("04:00").repeat_every(10.minutes()).times(50).run(cache_news);
```

The other (simpler) approach is that right now adding tasks at particular times uses strings. That's nice for humans, but I'd like to support using `NaiveTime` as well. Then you could just write
```rust
use chrono::{NaiveTime, Duration};
let start_time = NaiveTime::from_h0ms(4, 0, 0);
let interval= Duration::minutes(10);
std::iter::successors(Some(start_time), |&time| Some(time + interval))
  .take(50)
  .for_each(|time| scheduler.every(Weekday).at(time).run(cache_news));
```

-----

I don't like that tasks can block others, so `run_in_own_thread` is tempting. I think I'd also want some way to play nicely with `async` tasks, but it might be easiest for people to just call their executor's `spawn` or equivalent in their job, at least for now.

**Comment by joshterrill** [comment]
I do like the idea you mentioned for something like this:

```rust
scheduler.every(Weekday).at("04:00").repeat_every(10.minutes()).times(50).run(cache_news);
```

I think it would be not only intuitive but powerful.

Regarding the blocking tasks, if no changes would be made now, I think at the very least, the docs should be updated to state that tasks can block other tasks. At first glance, it actually doesn't seem that it would behave this way at all, and I had to do a little digging to figure out that that's what was causing my tasks to not start correctly.

**Comment by mdsherry** [comment]
Yeah, that's a gotcha that I hadn't really thought about. It should definitely be documented.

There are some tasks I want to get done this evening, but if I have time at the end I'll try getting started on these changes.

**Comment by joshterrill** [comment]
Great! Thanks!!

**Comment by mdsherry** [comment]
The bad news: `run_in_own_thread` doesn't really work with the constraints that jobs have. The problem is that they're `FnMut` to allow them to close over and modify whatever state they need, but once they're in a separate thread, you need to be careful that the function doesn't get called again before the first has finished. You could do it in a way that would satisfy the borrow checker by just moving the function to another thread right off the bat and using a channel to tell the other thread to call the function, but I'd rather let the user decide on an approach. I have updated the documentation, though, to note that `run_pending` will block, and suggest moving jobs to other threads.

I've finished the change to let `at` accept `NaiveTime`s as well as `&str`s. I'm looking at repeating tasks now.

**Comment by mdsherry** [comment]
Before I cut another release, is this the behaviour you were looking for?

**Comment by joshterrill** [comment]
Yes, I believe so! Could we get an updated Readme as well?

**Comment by joshterrill** [comment]
@mdsherry Any idea on when you'll cut a new release?

**Comment by mdsherry** [comment]
https://crates.io/crates/clokwerk/0.3.2
