### ISSUE TITLE
Every day is broken

### ISSUE THREAD

**Issue by irevoire** [mdsherry/clokwerk#2]
Hello,

I've just tried using your crate with this code:
```rust
    let mut scheduler = Scheduler::new();

    scheduler
        .every(1.day())
        .at("08:15")
        .and_every(1.day())
        .at("11:50")
        .and_every(1.day())
        .at("17:45")
        .run(move || {
            println!("Hello World");
    });

        thread::spawn(move || loop {
        scheduler.run_pending();
        thread::sleep(Duration::from_millis(500));
    });
```

And after some days the "Hello World" started being print like 10 times in a row at each specified time.

**Comment by mdsherry** [comment]
Hi!

Thanks for reporting this. I won't have a chance to look into this until next week, but I hope to get a chance on Monday.

**Comment by irevoire** [comment]
Hello back,

Good news I *think* I've found where the bug come from and it's probably not your crate 🎉 
I'll write a small example with nothing else than the one above and let it run for some days. If there is a bug I will come back to you.
But I think my problem come from another crate spawning threads when some error arise and then keeping multiple instance of my clokwerk thread.

Well, please don't spend time on this thing, I will reopen this issue if needed.
