### ISSUE TITLE
It two tasks are fired at the same will they execute parallely or serially?

### ISSUE THREAD

**Issue by asnimansari** [mdsherry/clokwerk#27]

**Comment by asnimansari** [comment]
How do I run tasks in separate threads?

**Comment by mdsherry** [comment]
To answer the question in the title, they run serially.

If you don't need to worry about synchronization or anything, you can just launch a new thread from your task to do the actual work, e.g.
```rust
scheduler.every(10.minutes()).run(|| {
  std::thread::spawn(|| {
    // Do work
  });
});
```

Or you can have a persistent thread reading from a channel, and your task pushes work onto the channel for the thread to process.

**Comment by asnimansari** [comment]
Thanks for the update @mdsherry
