### ISSUE TITLE
Document default timezone and add support for other timezones

### ISSUE THREAD

**Issue by hypirion** [mdsherry/clokwerk#3]
Hi, thanks for a nice library!

I think it would make sense to document what time zone this package works with by default, and possibly also support to specify the timezone on either the job to run or the scheduler itself. Does this sound reasonable?

**Comment by mdsherry** [comment]
I don't have time to finish it all tonight, but being able to specify the timezone for the scheduler seems reasonable. I've pushed the code changes, but I'd like to update the readme and examples too.

**Comment by mdsherry** [comment]
Version 0.2 supports arbitrary timezones, and is more explicit about the default timezone

**Comment by hypirion** [comment]
Thank you for this! :tada:
