### ISSUE TITLE
Don't print when a job is ran

### ISSUE THREAD

**Issue by NieDzejkob** [mdsherry/clokwerk#4]
Right now, when a job is executed, this is printed to my stdout for some reason:
```
Job { frequency: [RunConfig { base: Seconds(15), adjustment: None }], next_run: Some(2019-07-05T22:18:00.117662153+02:00), last_run: Some(2019-07-05T22:17:45.117662153+02:00), job: ??? }
```
This seems to be a leftover from debugging.

**Comment by mdsherry** [comment]
Thanks for catching that! I've just published 0.2.1 with a fix
