### ISSUE TITLE
Run Once Scheduling Missing

### ISSUE THREAD

**Issue by TNkemdilim** [mdsherry/clokwerk#7]
Firstly, thanks for the library.

It would be great to have a run once job supported i.e. run this task at `6:30 am` on `2nd October 2019`.

Suggestion:
```Rust
scheduler.on("02-10-2019")
    .by("14:20:17")
    // don't reschedule if `on` is called.
    .run(|| println!("Ran on 2nd October, 2019 by 14:20:17")); 
```
or

```Rust
scheduler.on("02-10-2019")
    .by("14:20:17")
    .run_once(|| println!("Ran on 2nd October, 2019 by 14:20:17"));
```

**Comment by mdsherry** [comment]
If you know the specific time and date to run something one, I'm uncertain as to the benefit this crate brings. You can get similar functionality from a thread running
```rust
use chrono::prelude::*;
use std::thread;
let target =
        DateTime::parse_from_rfc3339("2019-12-29T16:51:40-05:00").expect("Invalid date string").with_timezone(&Utc);
while Utc::now() < target {
    thread::sleep(std::time::Duration::from_millis(100));
}
do_the_thing();
```
I guess having multiple jobs like this running in the same thread could be useful? It feels like a mismatch for the general goal of this crate, though, which is to run recurring tasks.

I think a more general scheduler would want features like job cancelling and being able to scheduled tasks even after the watch loop has started, neither of which are possible with `clokwerk` as it is right now.
