### ISSUE TITLE
not able to use a `mpsc::channel` from a thread to a sched thread.

### ISSUE THREAD

**Issue by chino540off** [mdsherry/clokwerk#8]
Hello,

I would like to create a channel between a scheduled task, and another thread.

Here is an example of what I'm trying to do:
``` rust
extern crate clokwerk;

use clokwerk::TimeUnits;

fn main() {
    let (tx, rx) = std::sync::mpsc::channel();
    let mut scheduler = clokwerk::Scheduler::new();

    let th = std::thread::spawn(move || {
        let v = rx.recv().unwrap();

        assert!(v == 42);
    });

    let tx_clone = tx.clone();
    scheduler.every(30.seconds()).run(move || {
        tx_clone.send(42);
    });
}
```
and here is my compilation error:
```
error[E0277]: `std::sync::mpsc::Sender<i32>` cannot be shared between threads safely
  --> src/main.rs:16:35
   |
16 |     scheduler.every(30.seconds()).run(move || {
   |                                   ^^^ `std::sync::mpsc::Sender<i32>` cannot be shared between threads safely
   |
   = help: within `[closure@src/main.rs:16:39: 18:6 tx_clone:std::sync::mpsc::Sender<i32>]`, the trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Sender<i32>`
   = note: required because it appears within the type `[closure@src/main.rs:16:39: 18:6 tx_clone:std::sync::mpsc::Sender<i32>]`
```

I'm not an rust expert, but I'm wondering why `Job::run` need `std::marker::Sync` tasks?
More over, I'm reading the `std::thread::spawn` documentation, and it needs only tasks `std::marker::Send` (https://doc.rust-lang.org/std/thread/fn.spawn.html).

Maybe I'm wrong, but I would like to know why `Sync` marker is necessary here, and could it be removed? Maybe do you have a explaination, and a rust trick to pass over this issue.

Regards,

**Comment by mdsherry** [comment]
Nope, the `Sync` marker was unnecessary and has been removed from `clokwerk` 0.3. Thank you for pointing this out!
